module9-task2
htmlacademy-univer-javascript-1/2435413-kekstagram-4 pull request #11
Opened 2023-12-15 07:36 UTC by KristinaVavilina

2023-12-15 13:38 UTC, MaksimovG requested changes

2023-12-15 13:38 UTC, MaksimovG commented on index.html
> +              <input type="file" id="upload-file" class="img-upload__input  visually-hidden" name="filename" accept="image/*">
а required куда делось

2023-12-15 13:38 UTC, MaksimovG commented on js/submit-form.js
> +const ValuesCtrl = {
неговорящее название

2023-12-15 13:38 UTC, MaksimovG commented on js/submit-form.js
> +const STEP = 25;
относится к той же переменной - valuesGtrl

2023-12-15 13:38 UTC, MaksimovG commented on js/switch-effects.js
> +const Effects = {
Effect {
 NONE: {
style
}
}

2023-12-15 13:38 UTC, MaksimovG commented on js/switch-effects.js
> +let effect = Effects[nameEffect];
а здесь можно будет сделать .toUpperCase()

2023-12-16 12:34 UTC, MaksimovG requested changes

2023-12-16 12:34 UTC, MaksimovG commented on js/draw-big-picture.js
>      closeViewPopup();
ИНКАПСУЛЯЦИЯ, мы не делимся частью модуля с другими модулями. Кто-то еще может закрыть viewPopup. В другом модуле это уже другой попап, хоть и основан на тех же блоках. Можете вынести в какой-нибудь helper.js схожия для них операции. но никак не обработчики событий

2023-12-16 12:34 UTC, MaksimovG commented on js/submit-form.js
> +const ValuesScaleCtrl = {
что за Ctrl

2023-12-16 12:34 UTC, MaksimovG commented on js/submit-form.js
> +  valueCtrl.value = `${currentValueCtrl}%`;
этот непонятный набор букв по всему модулю

2023-12-16 12:34 UTC, MaksimovG commented on js/switch-effects.js
> +const Effects = {
я разве внутри NONE написал большими буквами?

2023-12-16 12:34 UTC, MaksimovG commented on js/switch-effects.js
> +  if (nameEffect === 'NONE') {
Вот этот NONE вынести в константу DEFAULT_EFFECT

2023-12-16 12:34 UTC, MaksimovG commented on js/switch-effects.js
> +export const onEffectsContainerClick = (evt) => {
зачем она экспортируется?

2023-12-16 12:34 UTC, MaksimovG commented on js/switch-effects.js
> +export const effectsContainer = form.querySelector('.img-upload__effects');
если сделать функцию снимающую обработчик не надо ее экспортировать. Делая экспорт одной функции вы уменьшите количество ненужных экспортов

2023-12-16 12:34 UTC, MaksimovG commented on js/switch-effects.js
> +export const onEffectsContainerClick = (evt) => {
создайте внутри модуля функцию которая будет снимать этот обработчик, и экспортируйте функцию, но не обработчик. Обработчик - шестеренка этого блока, а не ручка с помощью которой мы им управляем.

2023-12-16 12:34 UTC, MaksimovG commented on js/switch-effects.js
> +const Effects = {
Я назвал ее во множественном числе?

2023-12-16 12:50 UTC, KristinaVavilina commented on js/draw-big-picture.js
>      closeViewPopup();
да, я хотела попробовать, что будет, если ее экспортировать, но поняла, что ничего хорошего и забыла удалить это

2023-12-16 12:51 UTC, KristinaVavilina commented on js/submit-form.js
> +const ValuesScaleCtrl = {
control

2023-12-16 13:13 UTC, MaksimovG requested changes

2023-12-16 13:13 UTC, MaksimovG commented on js/submit-form.js
> +const ValuesScaleCtrl = {
Ну так и пишите

2023-12-16 13:13 UTC, MaksimovG commented on js/submit-form.js
> +const ValuesScaleCtrl = {
Потому что даже в сокращении зачем-то n потеряли.

2023-12-17 10:44 UTC, MaksimovG requested changes

2023-12-17 10:44 UTC, MaksimovG commented on js/submit-form.js
> +  valueCtrl.value = `${currentValueCtrl}%`;
Проигнорировано, я буду возвращать работу до тех пор пока или сокращение будет без ошибок и говорить, что это за сокращение, или пока  не будет написано currentValueControl что желалтельно. + это не только тут

2023-12-17 11:07 UTC, merged