module8-task1 draw-big-picture
htmlacademy-univer-javascript-1/2435413-kekstagram-4 pull request #8
Opened 2023-11-21 16:29 UTC by KristinaVavilina

2023-11-22 14:55 UTC, MaksimovG requested changes

2023-11-22 14:55 UTC, MaksimovG commented on js/draw-big-picture.js
> +  }
переписать на foreach

2023-11-22 14:55 UTC, MaksimovG commented on js/draw-big-picture.js
> +  });
вынести обработчик в отельную функцию, анонимные обработчики (а вы реализовали именно такой) нельзя снять. А обработчик с кнопки нужно снимать, если попап невиден

2023-11-22 14:55 UTC, MaksimovG commented on js/draw-big-picture.js
> +  document.removeEventListener('keydown', onDocumentKeydown);
а другие обработчики снять?

2023-11-22 14:55 UTC, MaksimovG commented on js/render-data.js
> +let photosNull = null;
просто photos

2023-11-22 14:55 UTC, MaksimovG commented on js/render-data.js
> +  const li = thumbnailsContainerElement.querySelectorAll('li');
li единственное число. А вы собираете здесь коллекцию (массив) а по критериям это должно быть множественное число. Да и само название li не очень

2023-11-24 09:03 UTC, KristinaVavilina commented on js/draw-big-picture.js
> +  document.removeEventListener('keydown', onDocumentKeydown);
Обработчики на фотографиях тоже нужно снять?

2023-11-24 17:53 UTC, MaksimovG approved these changes

2023-11-24 17:53 UTC, merged