module8-task2 render-comments
htmlacademy-univer-javascript-1/2435413-kekstagram-4 pull request #9
Opened 2023-11-28 08:10 UTC by KristinaVavilina

2023-11-29 15:13 UTC, MaksimovG requested changes

2023-11-29 15:13 UTC, MaksimovG commented on js/render-data.js
> +let endIndex;
что за объявление переменных без присваивания им каких либо значений

2023-11-29 15:13 UTC, MaksimovG commented on js/render-data.js
> +  thumbnailsContainerElement = document.querySelector('.social__comments');
это можно было сделать один раз там где объявляли пустую пременную

2023-11-29 15:13 UTC, MaksimovG commented on js/render-data.js
> +  thumbnailsContainerElement = document.querySelector('.social__comments');
название не подходиит по смыслу, это контейнер с комментариями

2023-11-29 15:13 UTC, MaksimovG commented on js/render-data.js
> +  });
thumbnailsContainerElement.innerHtml = '' заменяет все эти операции

2023-11-29 15:13 UTC, MaksimovG commented on js/render-data.js
> +    loadBtn.addEventListener('click', onBtnClick);
onLoadBtnClick

2023-12-01 14:10 UTC, MaksimovG requested changes

2023-12-01 14:10 UTC, MaksimovG commented on js/render-data.js
> +let thumbnailsContainerElement = document.querySelector('.social__comments');
почему let? мы разве будем менять эту переменную

2023-12-01 14:10 UTC, MaksimovG commented on js/render-data.js
> +    loadBtn.addEventListener('click', onBtnClick);
onLoadBtnClick

2023-12-01 14:10 UTC, MaksimovG commented on index.html
>            </div>
каким то боком мимо меня прошли изменения в main.js

`const COUNT_PHOTOS = 25;
const photos = generateDataForPhoto(COUNT_PHOTOS);
drawPictures(photos);

const pictures = document.querySelectorAll('.picture');

openViewPopup(pictures, photos);`

вот это вот выше наполовину неверно. Почему это мы вдруг вызываем открытие попапа в main.js ? Попап открывает при клике на мниатюру, а не просто так.

в main.js должно остаться только `const COUNT_PHOTOS = 25;
const photos = generateDataForPhoto(COUNT_PHOTOS);
drawPictures(photos);`

и уже внутри drawPictures мы вызываем открытие попапа при клике. Это созависимые модули

2023-12-01 14:10 UTC, MaksimovG commented on index.html
>            </div>
`export const openViewPopup = (pictures, photos) => {
  pictures.forEach((picture, index) =>  {
    picture.addEventListener('click', () => openPopup(photos[index]));
  });
};
`
логика навешивания обработчика должна быть в модуле drawPictures. Пересматривайте лекции все это разбиралось и показывалось. Особенно эту часть я даже код давал вам

2023-12-01 14:10 UTC, MaksimovG commented on js/draw-big-picture.js
>    });
логика навешивания обработчика должна быть в модуле drawPictures. Пересматривайте лекции все это разбиралось и показывалось. Особенно эту часть я даже код давал вам

2023-12-01 14:10 UTC, MaksimovG commented on js/draw-big-picture.js
> +  loadBtn.removeEventListener('click', onBtnClick);
onLoadBtnClick

2023-12-02 16:52 UTC, KristinaVavilina commented on js/render-data.js
> -  photos = data.slice();
не поняла

2023-12-02 17:28 UTC, MaksimovG requested changes

2023-12-02 17:28 UTC, MaksimovG commented on js/draw.js
> +import { openPopup } from './draw-big-picture.js';
draw что ? Что я должен понять из названия модуля? Перечитываем критерии

2023-12-02 17:28 UTC, MaksimovG commented on js/draw.js
> +import { openPopup } from './draw-big-picture.js';
Модуль - кирпич нашего приложения отвечающий за определенную функцию. Модуль отвечающий за отрисовку миниатюр, Модуль отвечающий за попап с большой картинкой и тд. И в соответствии с задачей - название файла

2023-12-02 17:28 UTC, MaksimovG commented on js/draw.js
> +  openViewPopup(photos);
первой - эта функция не нужна. Код из нее нужно перенести в замен вызова. Второе она ничего не открыает - так что ее название не корректно. КРИТЕРИИ!

2023-12-02 17:28 UTC, MaksimovG commented on js/draw.js
> +    picture.addEventListener('click', () => openPopup(photos[index]));
picture.addEventListener('click', () => openViewPopup(photos[index])); Именно тут логично openViewPopup название

2023-12-02 17:28 UTC, MaksimovG commented on js/render-data.js
> -  photos = data.slice();
```
const thumbnailsInit = (data) => {
  photos = data.slice();
```
не просто так мы записывали данный в переменную photos

2023-12-02 17:28 UTC, MaksimovG commented on js/render-data.js
> -  photos = data.slice();
у вас удален этот код

2023-12-02 17:28 UTC, MaksimovG commented on js/draw-big-picture.js
>    renderComments(photo.comments);
зачем эти функции и вся логика работы вынесена в непонятный модуль render -data. Есть модуль отвечающий за отображение большой фотографии кнопок и комментариев. В нем это и должно жить

2023-12-03 07:22 UTC, KristinaVavilina commented on js/render-data.js
> -  photos = data.slice();
const thumbnailsInit = () => {
  endIndex = Math.min(currentComments.length, endIndex + STEP_COMMENTS);
  sliceCurrentComments = currentComments.slice(0, endIndex);

Здесь у меня переменная sliceCurrentComments  это и есть старая photos, просто переименованная корректнее и slice теперь не всех комментариев, а только части. Это не то?

2023-12-03 17:27 UTC, MaksimovG requested changes

2023-12-03 17:27 UTC, MaksimovG commented on js/draw.js
> +import { openPopup } from './draw-big-picture.js';
Без изменений по этому комментарию. Название файла продолжает быть непонятным и не отражающим суть модуля

2023-12-03 17:27 UTC, MaksimovG commented on js/render-data.js
> -  photos = data.slice();
Конечно я запутался в вашем коде, вы сделали из нормальной работы какую-то кашу, с непонятными названиями файлов, с непонятными файлами render-datа, куда наложили кучу кода из модуля, который не надо было дробить на кучу частей

2023-12-03 17:27 UTC, MaksimovG commented on js/render-data.js
> +const thumbnailsInit = () => {
thumbnailsInit? Серьезно? Миниатюры Инит? Код внутри будет модуль миниатюр запускать? Сядьте и сделайте все заново. Ужасная каша. В лекции был дан код как отрисовать миниаютры.  Там же было показано как получить данные для модуля который будет отрисовывать большую фотографию. В лекции про большую фотографию был дан примерный скелет для модуля Большой картинки.

В main.js мы создаем переменную photos и получаем в нее наши моки. 
Ниже вызываем thumbnailsInit(photos).  ((renderMiniatures, renderThumbnails можно назвать)
В модулe thumbnails мы отрисовываем миниатюры, после отрисовки миниаютюр мы вешаем на них обработчик события по клику. В этом обработчике мы вычисляем данные для большой фотографии ( я советовал dataset атрибуты). После того как нашли нужные данные мы вызываем модуль view-popup.js: openViewPopup(данные для 1 фотографии)
Внутри этого вызванного модуля мы рисуем большую картинку, комментарии и  прочее

2023-12-03 17:51 UTC, KristinaVavilina commented on js/render-data.js
> +const thumbnailsInit = () => {
Неверно назвала функцию thumbnailsInit, она скорее CommentsInit... Исправила как нужно, мне кажется мой код идет по такому же сценарию, который вы дали. Просто некорректно назывались модули и функции, что запутало меня и Вас.

2023-12-04 09:52 UTC, MaksimovG requested changes

2023-12-04 09:52 UTC, MaksimovG commented on js/draw.js
> +import { openPopup } from './draw-big-picture.js';
Опять без изменений

2023-12-04 09:52 UTC, MaksimovG commented on js/render-data.js
> +const thumbnailsInit = () => {
Код идет не по сценарию.  Появился файл render-data который кто-то из вас выдумал и все дружно скопировали кривое решение. Название функции не изменилось. Вообще мне кажется вы не сделали коммит и не отправили его

2023-12-04 16:47 UTC, MaksimovG approved these changes

2023-12-04 16:47 UTC, merged